-- =============================================================================
-- Migration: App Countries seed
-- A dedicated lookup table for country / nationality data, reusable across the
-- app (clients, suppliers, itinerary destinations, profiles). Kept separate
-- from app_currencies because the currency catalog only covers countries that
-- have listed currencies (one row per currency, not per country), which would
-- produce duplicates and miss countries entirely.
--
-- Columns: id, name, iso_alpha2, iso_alpha3, dial_code, region, is_active
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.app_countries (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL UNIQUE,
    iso_alpha2  CHAR(2),
    iso_alpha3  CHAR(3),
    dial_code   TEXT,
    region      TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS: this is a shared lookup, readable by any authenticated user;
-- only super admins may modify it.
ALTER TABLE public.app_countries ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='app_countries' AND policyname='Users can view app countries') THEN
    CREATE POLICY "Users can view app countries" ON public.app_countries
      FOR SELECT USING (auth.role() = 'authenticated' OR public.is_super_admin());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='app_countries' AND policyname='Super admins can manage app countries') THEN
    CREATE POLICY "Super admins can manage app countries" ON public.app_countries
      FOR ALL USING (public.is_super_admin());
  END IF;
END $$;

INSERT INTO public.app_countries (name, iso_alpha2, iso_alpha3, dial_code, region) VALUES
  ('Afghanistan', 'AF', 'AFG', '+93', 'Asia'),
  ('Albania', 'AL', 'ALB', '+355', 'Europe'),
  ('Algeria', 'DZ', 'DZA', '+213', 'Africa'),
  ('Andorra', 'AD', 'AND', '+376', 'Europe'),
  ('Angola', 'AO', 'AGO', '+244', 'Africa'),
  ('Antigua and Barbuda', 'AG', 'ATG', '+1-268', 'Americas'),
  ('Argentina', 'AR', 'ARG', '+54', 'Americas'),
  ('Armenia', 'AM', 'ARM', '+374', 'Asia'),
  ('Australia', 'AU', 'AUS', '+61', 'Oceania'),
  ('Austria', 'AT', 'AUT', '+43', 'Europe'),
  ('Azerbaijan', 'AZ', 'AZE', '+994', 'Asia'),
  ('Bahamas', 'BS', 'BHS', '+1-242', 'Americas'),
  ('Bahrain', 'BH', 'BHR', '+973', 'Asia'),
  ('Bangladesh', 'BD', 'BGD', '+880', 'Asia'),
  ('Barbados', 'BB', 'BRB', '+1-246', 'Americas'),
  ('Belarus', 'BY', 'BLR', '+375', 'Europe'),
  ('Belgium', 'BE', 'BEL', '+32', 'Europe'),
  ('Belize', 'BZ', 'BLZ', '+501', 'Americas'),
  ('Benin', 'BJ', 'BEN', '+229', 'Africa'),
  ('Bhutan', 'BT', 'BTN', '+975', 'Asia'),
  ('Bolivia', 'BO', 'BOL', '+591', 'Americas'),
  ('Bosnia and Herzegovina', 'BA', 'BIH', '+387', 'Europe'),
  ('Botswana', 'BW', 'BWA', '+267', 'Africa'),
  ('Brazil', 'BR', 'BRA', '+55', 'Americas'),
  ('Brunei', 'BN', 'BRN', '+673', 'Asia'),
  ('Bulgaria', 'BG', 'BGR', '+359', 'Europe'),
  ('Burkina Faso', 'BF', 'BFA', '+226', 'Africa'),
  ('Burundi', 'BI', 'BDI', '+257', 'Africa'),
  ('Cabo Verde', 'CV', 'CPV', '+238', 'Africa'),
  ('Cambodia', 'KH', 'KHM', '+855', 'Asia'),
  ('Cameroon', 'CM', 'CMR', '+237', 'Africa'),
  ('Canada', 'CA', 'CAN', '+1', 'Americas'),
  ('Central African Republic', 'CF', 'CAF', '+236', 'Africa'),
  ('Chad', 'TD', 'TCD', '+235', 'Africa'),
  ('Chile', 'CL', 'CHL', '+56', 'Americas'),
  ('China', 'CN', 'CHN', '+86', 'Asia'),
  ('Colombia', 'CO', 'COL', '+57', 'Americas'),
  ('Comoros', 'KM', 'COM', '+269', 'Africa'),
  ('Congo (Democratic Republic)', 'CD', 'COD', '+243', 'Africa'),
  ('Congo (Republic)', 'CG', 'COG', '+242', 'Africa'),
  ('Costa Rica', 'CR', 'CRI', '+506', 'Americas'),
  ('Cote d''Ivoire', 'CI', 'CIV', '+225', 'Africa'),
  ('Croatia', 'HR', 'HRV', '+385', 'Europe'),
  ('Cuba', 'CU', 'CUB', '+53', 'Americas'),
  ('Cyprus', 'CY', 'CYP', '+357', 'Europe'),
  ('Czechia', 'CZ', 'CZE', '+420', 'Europe'),
  ('Denmark', 'DK', 'DNK', '+45', 'Europe'),
  ('Djibouti', 'DJ', 'DJI', '+253', 'Africa'),
  ('Dominica', 'DM', 'DMA', '+1-767', 'Americas'),
  ('Dominican Republic', 'DO', 'DOM', '+1-809', 'Americas'),
  ('Ecuador', 'EC', 'ECU', '+593', 'Americas'),
  ('Egypt', 'EG', 'EGY', '+20', 'Africa'),
  ('El Salvador', 'SV', 'SLV', '+503', 'Americas'),
  ('Equatorial Guinea', 'GQ', 'GNQ', '+240', 'Africa'),
  ('Eritrea', 'ER', 'ERI', '+291', 'Africa'),
  ('Estonia', 'EE', 'EST', '+372', 'Europe'),
  ('Eswatini', 'SZ', 'SWZ', '+268', 'Africa'),
  ('Ethiopia', 'ET', 'ETH', '+251', 'Africa'),
  ('Fiji', 'FJ', 'FJI', '+679', 'Oceania'),
  ('Finland', 'FI', 'FIN', '+358', 'Europe'),
  ('France', 'FR', 'FRA', '+33', 'Europe'),
  ('Gabon', 'GA', 'GAB', '+241', 'Africa'),
  ('Gambia', 'GM', 'GMB', '+220', 'Africa'),
  ('Georgia', 'GE', 'GEO', '+995', 'Asia'),
  ('Germany', 'DE', 'DEU', '+49', 'Europe'),
  ('Ghana', 'GH', 'GHA', '+233', 'Africa'),
  ('Greece', 'GR', 'GRC', '+30', 'Europe'),
  ('Grenada', 'GD', 'GRD', '+1-473', 'Americas'),
  ('Guatemala', 'GT', 'GTM', '+502', 'Americas'),
  ('Guinea', 'GN', 'GIN', '+224', 'Africa'),
  ('Guinea-Bissau', 'GW', 'GNB', '+245', 'Africa'),
  ('Guyana', 'GY', 'GUY', '+592', 'Americas'),
  ('Haiti', 'HT', 'HTI', '+509', 'Americas'),
  ('Honduras', 'HN', 'HND', '+504', 'Americas'),
  ('Hungary', 'HU', 'HUN', '+36', 'Europe'),
  ('Iceland', 'IS', 'ISL', '+354', 'Europe'),
  ('India', 'IN', 'IND', '+91', 'Asia'),
  ('Indonesia', 'ID', 'IDN', '+62', 'Asia'),
  ('Iran', 'IR', 'IRN', '+98', 'Asia'),
  ('Iraq', 'IQ', 'IRQ', '+964', 'Asia'),
  ('Ireland', 'IE', 'IRL', '+353', 'Europe'),
  ('Israel', 'IL', 'ISR', '+972', 'Asia'),
  ('Italy', 'IT', 'ITA', '+39', 'Europe'),
  ('Jamaica', 'JM', 'JAM', '+1-876', 'Americas'),
  ('Japan', 'JP', 'JPN', '+81', 'Asia'),
  ('Jordan', 'JO', 'JOR', '+962', 'Asia'),
  ('Kazakhstan', 'KZ', 'KAZ', '+7', 'Asia'),
  ('Kenya', 'KE', 'KEN', '+254', 'Africa'),
  ('Kiribati', 'KI', 'KIR', '+686', 'Oceania'),
  ('Korea (North)', 'KP', 'PRK', '+850', 'Asia'),
  ('Korea (South)', 'KR', 'KOR', '+82', 'Asia'),
  ('Kuwait', 'KW', 'KWT', '+965', 'Asia'),
  ('Kyrgyzstan', 'KG', 'KGZ', '+996', 'Asia'),
  ('Laos', 'LA', 'LAO', '+856', 'Asia'),
  ('Latvia', 'LV', 'LVA', '+371', 'Europe'),
  ('Lebanon', 'LB', 'LBN', '+961', 'Asia'),
  ('Lesotho', 'LS', 'LSO', '+266', 'Africa'),
  ('Liberia', 'LR', 'LBR', '+231', 'Africa'),
  ('Libya', 'LY', 'LBY', '+218', 'Africa'),
  ('Liechtenstein', 'LI', 'LIE', '+423', 'Europe'),
  ('Lithuania', 'LT', 'LTU', '+370', 'Europe'),
  ('Luxembourg', 'LU', 'LUX', '+352', 'Europe'),
  ('Madagascar', 'MG', 'MDG', '+261', 'Africa'),
  ('Malawi', 'MW', 'MWI', '+265', 'Africa'),
  ('Malaysia', 'MY', 'MYS', '+60', 'Asia'),
  ('Maldives', 'MV', 'MDV', '+960', 'Asia'),
  ('Mali', 'ML', 'MLI', '+223', 'Africa'),
  ('Malta', 'MT', 'MLT', '+356', 'Europe'),
  ('Marshall Islands', 'MH', 'MHL', '+692', 'Oceania'),
  ('Mauritania', 'MR', 'MRT', '+222', 'Africa'),
  ('Mauritius', 'MU', 'MUS', '+230', 'Africa'),
  ('Mexico', 'MX', 'MEX', '+52', 'Americas'),
  ('Micronesia', 'FM', 'FSM', '+691', 'Oceania'),
  ('Moldova', 'MD', 'MDA', '+373', 'Europe'),
  ('Monaco', 'MC', 'MCO', '+377', 'Europe'),
  ('Mongolia', 'MN', 'MNG', '+976', 'Asia'),
  ('Montenegro', 'ME', 'MNE', '+382', 'Europe'),
  ('Morocco', 'MA', 'MAR', '+212', 'Africa'),
  ('Mozambique', 'MZ', 'MOZ', '+258', 'Africa'),
  ('Myanmar', 'MM', 'MMR', '+95', 'Asia'),
  ('Namibia', 'NA', 'NAM', '+264', 'Africa'),
  ('Nauru', 'NR', 'NRU', '+674', 'Oceania'),
  ('Nepal', 'NP', 'NPL', '+977', 'Asia'),
  ('Netherlands', 'NL', 'NLD', '+31', 'Europe'),
  ('New Zealand', 'NZ', 'NZL', '+64', 'Oceania'),
  ('Nicaragua', 'NI', 'NIC', '+505', 'Americas'),
  ('Niger', 'NE', 'NER', '+227', 'Africa'),
  ('Nigeria', 'NG', 'NGA', '+234', 'Africa'),
  ('North Macedonia', 'MK', 'MKD', '+389', 'Europe'),
  ('Norway', 'NO', 'NOR', '+47', 'Europe'),
  ('Oman', 'OM', 'OMN', '+968', 'Asia'),
  ('Pakistan', 'PK', 'PAK', '+92', 'Asia'),
  ('Palau', 'PW', 'PLW', '+680', 'Oceania'),
  ('Palestine', 'PS', 'PSE', '+970', 'Asia'),
  ('Panama', 'PA', 'PAN', '+507', 'Americas'),
  ('Papua New Guinea', 'PG', 'PNG', '+675', 'Oceania'),
  ('Paraguay', 'PY', 'PRY', '+595', 'Americas'),
  ('Peru', 'PE', 'PER', '+51', 'Americas'),
  ('Philippines', 'PH', 'PHL', '+63', 'Asia'),
  ('Poland', 'PL', 'POL', '+48', 'Europe'),
  ('Portugal', 'PT', 'PRT', '+351', 'Europe'),
  ('Qatar', 'QA', 'QAT', '+974', 'Asia'),
  ('Romania', 'RO', 'ROU', '+40', 'Europe'),
  ('Russia', 'RU', 'RUS', '+7', 'Europe'),
  ('Rwanda', 'RW', 'RWA', '+250', 'Africa'),
  ('Saint Kitts and Nevis', 'KN', 'KNA', '+1-869', 'Americas'),
  ('Saint Lucia', 'LC', 'LCA', '+1-758', 'Americas'),
  ('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1-784', 'Americas'),
  ('Samoa', 'WS', 'WSM', '+685', 'Oceania'),
  ('San Marino', 'SM', 'SMR', '+378', 'Europe'),
  ('Sao Tome and Principe', 'ST', 'STP', '+239', 'Africa'),
  ('Saudi Arabia', 'SA', 'SAU', '+966', 'Asia'),
  ('Senegal', 'SN', 'SEN', '+221', 'Africa'),
  ('Serbia', 'RS', 'SRB', '+381', 'Europe'),
  ('Seychelles', 'SC', 'SYC', '+248', 'Africa'),
  ('Sierra Leone', 'SL', 'SLE', '+232', 'Africa'),
  ('Singapore', 'SG', 'SGP', '+65', 'Asia'),
  ('Slovakia', 'SK', 'SVK', '+421', 'Europe'),
  ('Slovenia', 'SI', 'SVN', '+386', 'Europe'),
  ('Solomon Islands', 'SB', 'SLB', '+677', 'Oceania'),
  ('Somalia', 'SO', 'SOM', '+252', 'Africa'),
  ('South Africa', 'ZA', 'ZAF', '+27', 'Africa'),
  ('South Sudan', 'SS', 'SSD', '+211', 'Africa'),
  ('Spain', 'ES', 'ESP', '+34', 'Europe'),
  ('Sri Lanka', 'LK', 'LKA', '+94', 'Asia'),
  ('Sudan', 'SD', 'SDN', '+249', 'Africa'),
  ('Suriname', 'SR', 'SUR', '+597', 'Americas'),
  ('Sweden', 'SE', 'SWE', '+46', 'Europe'),
  ('Switzerland', 'CH', 'CHE', '+41', 'Europe'),
  ('Syria', 'SY', 'SYR', '+963', 'Asia'),
  ('Taiwan', 'TW', 'TWN', '+886', 'Asia'),
  ('Tajikistan', 'TJ', 'TJK', '+992', 'Asia'),
  ('Tanzania', 'TZ', 'TZA', '+255', 'Africa'),
  ('Thailand', 'TH', 'THA', '+66', 'Asia'),
  ('Timor-Leste', 'TL', 'TLS', '+670', 'Asia'),
  ('Togo', 'TG', 'TGO', '+228', 'Africa'),
  ('Tonga', 'TO', 'TON', '+676', 'Oceania'),
  ('Trinidad and Tobago', 'TT', 'TTO', '+1-868', 'Americas'),
  ('Tunisia', 'TN', 'TUN', '+216', 'Africa'),
  ('Turkey', 'TR', 'TUR', '+90', 'Asia'),
  ('Turkmenistan', 'TM', 'TKM', '+993', 'Asia'),
  ('Tuvalu', 'TV', 'TUV', '+688', 'Oceania'),
  ('Uganda', 'UG', 'UGA', '+256', 'Africa'),
  ('Ukraine', 'UA', 'UKR', '+380', 'Europe'),
  ('United Arab Emirates', 'AE', 'ARE', '+971', 'Asia'),
  ('United Kingdom', 'GB', 'GBR', '+44', 'Europe'),
  ('United States', 'US', 'USA', '+1', 'Americas'),
  ('Uruguay', 'UY', 'URY', '+598', 'Americas'),
  ('Uzbekistan', 'UZ', 'UZB', '+998', 'Asia'),
  ('Vanuatu', 'VU', 'VUT', '+678', 'Oceania'),
  ('Vatican City', 'VA', 'VAT', '+39', 'Europe'),
  ('Venezuela', 'VE', 'VEN', '+58', 'Americas'),
  ('Vietnam', 'VN', 'VNM', '+84', 'Asia'),
  ('Yemen', 'YE', 'YEM', '+967', 'Asia'),
  ('Zambia', 'ZM', 'ZMB', '+260', 'Africa'),
  ('Zimbabwe', 'ZW', 'ZWE', '+263', 'Africa')
ON CONFLICT (name) DO UPDATE
  SET iso_alpha2 = EXCLUDED.iso_alpha2,
      iso_alpha3 = EXCLUDED.iso_alpha3,
      dial_code  = EXCLUDED.dial_code,
      region     = EXCLUDED.region,
      is_active  = EXCLUDED.is_active;

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';